# Generated by Django 5.2.6 on 2025-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_phone'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-list_date']},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['list_date'], name='listings_li_list_da_153ce3_idx'),
        ),
    ]
