# Generated by Django 5.2.6 on 2025-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=27297361, max_length=20),
            preserve_default=False,
        ),
    ]
